title: Just some ramblings..
description: >-
  Not enough room in the hippocampus, and until i can get my hands on neuralink,
  ill just put stuff here.
baseurl: ''
url: ''
github_username: codeChutney
author: amyth
theme: minima
plugins:
  - jekyll-feed
email: a_myhtl@yahoo.com
